### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by andsydev** [Psycrow101/Blender-3D-XOM-plugin#2]
Whenever i try to enable the addon in Blender 2.79, this specific error pops up everytime i do it:

![image](https://github.com/Psycrow101/Blender-3D-XOM-plugin/assets/151461018/5cc56307-b392-4259-80c7-300c8ba8e65f)

**Comment by Psycrow101** [comment]
Hi @andsydev. It looks like you are trying to enable the latest version of this addon. For Blender 2.79 you need to install this version [xom_import.py](https://github.com/Psycrow101/Blender-3D-XOM-plugin/releases/download/1.0.3/xom_import.py)
